[package]
name = "touptek"
version = "0.1.0"
authors = ["whitequark <whitequark@whitequark.org>"]

[dependencies]
libc = "*"
bitflags = "0.2"

[dependencies.fourcc]
git = "git://github.com/rust-lang/fourcc"
