[package]
name = "touptek"
version = "0.1.0"
authors = ["whitequark <whitequark@whitequark.org>"]

[dependencies]
libc = "*"
bitflags = "*"

[dependencies.fourcc]
git = "git://github.com/whitequark/fourcc"
